### ISSUE TITLE
RSS feed is broken

### ISSUE THREAD

**Issue by raffaelj** [simpleid/simpleid.github.io#13]
It looks like a missing `layout: null` in `rss.xml.liquid`. I never used 11ty, so I'm not sure about the whole deploy chain, but after a short search I found `<div class="wrapper">` in https://github.com/simpleid/simpleid.github.io/blob/gh-pages/rss.xml, which indicates the use of the default layout.

I would love to be able to subscribe to the release notes again. And many thanks for this software.

**Comment by kelvinmo** [comment]
There is an issue with an upstream node package which means HTML is not escaped correctly in the RSS: https://github.com/jeremenichelli/eleventy-xml-plugin/issues/6

**Comment by raffaelj** [comment]
That was fast. Thanks for the fix.
